.PHONY: clean All

All:
	@echo "----------Building project:[ week2-adt -  ]----------"
	@cd "week2-adt" && "$(MAKE)" -f  "week2-adt.mk"
clean:
	@echo "----------Cleaning project:[ week2-adt -  ]----------"
	@cd "week2-adt" && "$(MAKE)" -f  "week2-adt.mk" clean
